openapi: 3.0.1
info:
  description: "This is the definition for general components API"
  version: "1.0.0"
  title: "General Components API"

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: "The error message"    

    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          description: "The success message"

  parameters:
    x-request-id:
      name: x-request-id
      description: "The request ID"
      in: header
      required: true
      schema:
        type: string
    x-ip-address:
      name: x-ip-address
      description: "The IP address"
      in: header
      required: false
      schema:
        type: string
    Authorization:
      name: Authorization
      description: "The authorization token"
      in: header
      required: true
      schema:
        type: string
  
  headers:
    Content-Language:
      description: "The content language"
      schema:
        type: string

    Access-Control-Allow-Origin:
      description: "The access control allow origin"
      schema:
        type: string

    Access-Control-Allow-Methods:
      description: "The access control allow methods"
      schema:
        type: string

    Access-Control-Allow-Headers:
      description: "The access control allow headers"
      schema:
        type: string
    
    x-jws-signature:
      description: "The JWS signature"
      schema:
        type: string

  responses:
    Response400:
      description: "Bad request"
      headers:
        Content-Language:
          $ref: "#/components/headers/Content-Language"
        Access-Control-Allow-Origin:
          $ref: "#/components/headers/Access-Control-Allow-Origin"
        Access-Control-Allow-Methods:
          $ref: "#/components/headers/Access-Control-Allow-Methods"
        Access-Control-Allow-Headers:
          $ref: "#/components/headers/Access-Control-Allow-Headers"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    
    Response401:
      description: "Unauthorized"
      headers:
        Content-Language:
          $ref: "#/components/headers/Content-Language"
        Access-Control-Allow-Origin:
          $ref: "#/components/headers/Access-Control-Allow-Origin"
        Access-Control-Allow-Methods:
          $ref: "#/components/headers/Access-Control-Allow-Methods"
        Access-Control-Allow-Headers:
          $ref: "#/components/headers/Access-Control-Allow-Headers"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    Response403:
      description: "Forbidden"
      headers:
        Content-Language:
          $ref: "#/components/headers/Content-Language"
        Access-Control-Allow-Origin:
          $ref: "#/components/headers/Access-Control-Allow-Origin"
        Access-Control-Allow-Methods:
          $ref: "#/components/headers/Access-Control-Allow-Methods"
        Access-Control-Allow-Headers:
          $ref: "#/components/headers/Access-Control-Allow-Headers"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    Response404:
      description: "Not found"
      headers:
        Content-Language:
          $ref: "#/components/headers/Content-Language"
        Access-Control-Allow-Origin:
          $ref: "#/components/headers/Access-Control-Allow-Origin"
        Access-Control-Allow-Methods:
          $ref: "#/components/headers/Access-Control-Allow-Methods"
        Access-Control-Allow-Headers:
          $ref: "#/components/headers/Access-Control-Allow-Headers"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    Response409:
      description: "Conflict"
      headers:
        Content-Language:
          $ref: "#/components/headers/Content-Language"
        Access-Control-Allow-Origin:
          $ref: "#/components/headers/Access-Control-Allow-Origin"
        Access-Control-Allow-Methods:
          $ref: "#/components/headers/Access-Control-Allow-Methods"
        Access-Control-Allow-Headers:
          $ref: "#/components/headers/Access-Control-Allow-Headers"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    Response429:
      description: "Too many requests"
      headers:
        Content-Language:
          $ref: "#/components/headers/Content-Language"
        Access-Control-Allow-Origin:
          $ref: "#/components/headers/Access-Control-Allow-Origin"
        Access-Control-Allow-Methods:
          $ref: "#/components/headers/Access-Control-Allow-Methods"
        Access-Control-Allow-Headers:
          $ref: "#/components/headers/Access-Control-Allow-Headers"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    Response500:
      description: "Internal server error"
      headers:
        Content-Language:
          $ref: "#/components/headers/Content-Language"
        Access-Control-Allow-Origin:
          $ref: "#/components/headers/Access-Control-Allow-Origin"
        Access-Control-Allow-Methods:
          $ref: "#/components/headers/Access-Control-Allow-Methods"
        Access-Control-Allow-Headers:
          $ref: "#/components/headers/Access-Control-Allow-Headers"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    

